# Serenity BDD Configuration
serenity.project.name = GitHub Actions Learning Project

# Root package for tests
serenity.test.root=org.example

# Enable HTML reports
serenity.html.report.enabled=true
serenity.take.screenshots=FOR_FAILURES
serenity.batch.process.wait.time=30

# Output directory for Serenity reports
serenity.output.directory=target/site/serenity