# Serenity BDD Configuration
serenity.project.name = GitHub Actions Learning Project

# Root package for tests
serenity.test.root=com.example

# Enable HTML reports
serenity.html.report.enabled=true
serenity.take.screenshots=FOR_EACH_TEST
serenity.batch.process.wait.time=30